language: python
python:
  - "3.4.3"
  - "3.5.1"

env:
  - DJANGO=1.8.5 MIGRATE='./manage.py migrate'

script:
  - python manage.py migrate

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run manage.py test BlogDAS/ -v 2

after_success:
  - coveralls
